class AddJournalLanguage < ActiveRecord::Migration
  def self.up
    if !ActiveRecord::Base.configurations[RAILS_ENV].include?('encoding') or ActiveRecord::Base.configurations[RAILS_ENV]['encoding'] != 'utf8'
      puts "Migration failed because database connection does not use the right encoding."
      puts "Your database.yml config file must include the encoding key with value 'utf8'."
      exit
    end

    add_column :journals, :language_id, :integer, :after => :current_entry_id, :null => true, :default => nil
    add_column :languages, :localized_name, :string, :length => 50, :null => true, :default => nil, :after => :long_name
    add_column :languages, :allowed_in_profile, :boolean, :default => false, :null => false, :after => :localized_name

    Language.reset_column_information

    # Add new languages for people to choose as their journal language:
    # Languages come from the ISO 639 list 
    Language.find_by_short_name('en').update_attributes({:allowed_in_profile => true})
    Language.create!(:short_name => 'aa', :long_name => 'Afar', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ab', :long_name => 'Abkhazian', :localized_name => 'аҧсуа бызшәа', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ae', :long_name => 'Avestan', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'af', :long_name => 'Afrikaans', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ak', :long_name => 'Akan', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'am', :long_name => 'Amharic', :localized_name => 'አማርኛ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ar', :long_name => 'Arabic', :localized_name => 'العربية', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'as', :long_name => 'Assamese', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'av', :long_name => 'Avar', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ay', :long_name => 'Aymara', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'az', :long_name => 'Azerbaijani', :localized_name => 'azərbaycan', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ba', :long_name => 'Bashkir', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'be', :long_name => 'Belarusian', :localized_name => 'Беларуская', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'bg', :long_name => 'Bulgarian', :localized_name => 'Български', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'bh', :long_name => 'Bihari', :localized_name => 'भोजपुरी', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'bi', :long_name => 'Bislama', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'bm', :long_name => 'Bambara', :localized_name => 'Bamanankan', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'bn', :long_name => 'Bengali', :localized_name => 'বাংলা', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'bo', :long_name => 'Tibetan', :localized_name => 'བོད་ཡིག', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'br', :long_name => 'Breton', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'bs', :long_name => 'Bosnian', :localized_name => 'Bosanski', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ca', :long_name => 'Catalan', :localized_name => 'Català', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ce', :long_name => 'Chechen', :localized_name => 'нохчийн мотт', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ch', :long_name => 'Chamorro', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'co', :long_name => 'Corsican', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'cr', :long_name => 'Cree', :localized_name => 'ᓀᐦᐃᔭᐍᐏᐣ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'cs', :long_name => 'Czech', :localized_name => 'Čeština', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'cu', :long_name => 'Old Church Slavonic', :localized_name => 'ѩзыкъ словѣньскъ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'cv', :long_name => 'Chuvash', :localized_name => 'чӑваш чӗлхи', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'cy', :long_name => 'Welsh', :localized_name => 'Cymraeg', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'da', :long_name => 'Danish', :localized_name => 'Dansk', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'de', :long_name => 'German', :localized_name => 'Deutsch', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'dv', :long_name => 'Dhivehi', :localized_name => 'ދިވެހި', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'dz', :long_name => 'Dzongkha', :localized_name => 'རྫོང་ཁ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ee', :long_name => 'Ewe', :localized_name => 'Ɛʋɛ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'el', :long_name => 'Greek', :localized_name => 'Ελληνικά', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'eo', :long_name => 'Esperanto', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'es', :long_name => 'Spanish', :localized_name => 'Español', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'et', :long_name => 'Estonian', :localized_name => 'Eesti', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'eu', :long_name => 'Basque', :localized_name => 'Euskera', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'fa', :long_name => 'Persian', :localized_name => 'فارسی', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ff', :long_name => 'Fulah', :localized_name => 'Fulfulde', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'fi', :long_name => 'Finnish', :localized_name => 'Suomi', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'fj', :long_name => 'Fijian', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'fo', :long_name => 'Faeroese', :localized_name => 'Føroyskt', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'fr', :long_name => 'French', :localized_name => 'Français', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'fy', :long_name => 'Frisian', :localized_name => 'Frysk', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ga', :long_name => 'Irish', :localized_name => 'Gaeilge', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'gd', :long_name => 'Scottish Gaelic', :localized_name => 'Gàidhlig', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'gl', :long_name => 'Galician', :localized_name => 'Galego', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'gn', :long_name => 'Guaraní', :localized_name => "Avañe'ẽ", :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'gu', :long_name => 'Gujarati', :localized_name => 'ગુજરાતી', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'gv', :long_name => 'Manx', :localized_name => 'Gaelg', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ha', :long_name => 'Hausa', :localized_name => 'هَوُسَ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'he', :long_name => 'Hebrew', :localized_name => 'עברית', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'hi', :long_name => 'Hindi', :localized_name => 'हिन्दी', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ho', :long_name => 'Hiri Motu', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'hr', :long_name => 'Croatian', :localized_name => 'Hrvatski', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'hu', :long_name => 'Hungarian', :localized_name => 'Magyar', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'hy', :long_name => 'Armenian', :localized_name => 'Հայերեն', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'hz', :long_name => 'Herero', :localized_name => 'Otjiherero', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ia', :long_name => 'Interlingua', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'id', :long_name => 'Indonesian', :localized_name => 'Bahasa Indonesia', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ie', :long_name => 'Interlingue', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ig', :long_name => 'Igbo', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ik', :long_name => 'Inupiaq', :localized_name => 'Iñupiaq', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'is', :long_name => 'Icelandic', :localized_name => 'Íslenska', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'it', :long_name => 'Italian', :localized_name => 'Italiano', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'iu', :long_name => 'Inuktitut', :localized_name => 'ᐃᓄᒃᑎᑐᑦ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ja', :long_name => 'Japanese', :localized_name => '日本語', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'jv', :long_name => 'Javanese', :localized_name => 'basa Jawa', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ka', :long_name => 'Georgian', :localized_name => 'ქართული', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'kg', :long_name => 'Kongo', :localized_name => 'KiKongo', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ki', :long_name => 'Gikuyu', :localized_name => 'Gĩkũyũ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'kj', :long_name => 'Kwanyama', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'kk', :long_name => 'Kazakh', :localized_name => 'Қазақ тілі', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'kl', :long_name => 'Kalaallisut', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'km', :long_name => 'Khmer', :localized_name => 'ភាសាខ្មែរ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'kn', :long_name => 'Kannada', :localized_name => 'ಕನ್ನಡ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ko', :long_name => 'Korean', :localized_name => '한국어', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'kr', :long_name => 'Kanuri', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ks', :long_name => 'Kashmiri', :localized_name => 'कश्मीरी', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ku', :long_name => 'Kurdish', :localized_name => 'Kurdî', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'kv', :long_name => 'Komi', :localized_name => 'коми кыв', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'kw', :long_name => 'Cornish', :localized_name => 'Kernewek', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ky', :long_name => 'Kirghiz', :localized_name => 'кыргыз тили', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'la', :long_name => 'Latin', :localized_name => 'Latina', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'lb', :long_name => 'Luxembourgish', :localized_name => 'Lëtzebuergesch', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'lg', :long_name => 'Luganda', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ln', :long_name => 'Lingala', :localized_name => 'Lingála', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'lo', :long_name => 'Laothian', :localized_name => 'ພາສາລາວ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'lt', :long_name => 'Lithuanian', :localized_name => 'Lietuvių', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'lv', :long_name => 'Latvian', :localized_name => 'Latviešu', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'mg', :long_name => 'Malagasy', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'mh', :long_name => 'Marshallese', :localized_name => 'Kajin M̧ajeļ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'mi', :long_name => 'Maori', :localized_name => 'te reo Māori', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'mk', :long_name => 'Macedonian', :localized_name => 'Македонски', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ml', :long_name => 'Malayalam', :localized_name => 'മലയാളം', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'mn', :long_name => 'Mongolian', :localized_name => 'Монгол', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'mo', :long_name => 'Moldavian', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'mr', :long_name => 'Marathi', :localized_name => 'मराठी', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ms', :long_name => 'Malay', :localized_name => 'Bahasa Melayu', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'mt', :long_name => 'Maltese', :localized_name => 'Malti', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'my', :long_name => 'Burmese', :localized_name => 'ဗမာစာ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'na', :long_name => 'Nauruan', :localized_name => 'Ekakairũ Naoero', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'nd', :long_name => 'North Ndebele', :localized_name => 'isiNdebele', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ne', :long_name => 'Nepali', :localized_name => 'नेपाली', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ng', :long_name => 'Ndonga', :localized_name => 'Owambo', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'nl', :long_name => 'Dutch', :localized_name => 'Nederlands', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'nb', :long_name => 'Norwegian Bokmål', :localized_name => 'Bokmål', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'nn', :long_name => 'Norwegian Nynorsk', :localized_name => 'Nynorsk', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'nr', :long_name => 'South Ndebele', :localized_name => 'isiNdebele', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'nv', :long_name => 'Navajo', :localized_name => 'Diné bizaad; Dinékʼehǰí', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ny', :long_name => 'Chichewa', :localized_name => 'chiCheŵa', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'oc', :long_name => 'Occitan', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'om', :long_name => 'Oromo', :localized_name => 'Afaan Oromoo', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'or', :long_name => 'Oriya', :localized_name => 'ଓଡ଼ିଆ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'os', :long_name => 'Ossetic', :localized_name => 'Ирон æвзаг', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'pa', :long_name => 'Punjabi', :localized_name => 'ਪੰਜਾਬੀ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'pi', :long_name => 'Pāli', :localized_name => 'पाऴि', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'pl', :long_name => 'Polish', :localized_name => 'Polski', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ps', :long_name => 'Pashto', :localized_name => 'پښتو', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'pt', :long_name => 'Portuguese', :localized_name => 'Português', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'qu', :long_name => 'Quechua', :localized_name => 'Runa Simi', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'rm', :long_name => 'Rhaeto-Romance', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'rn', :long_name => 'Kirundi', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ro', :long_name => 'Romanian', :localized_name => 'Română', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ru', :long_name => 'Russian', :localized_name => 'Русский', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'rw', :long_name => 'Kinyarwanda', :localized_name => 'Ikinyarwanda', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sa', :long_name => 'Sanskrit', :localized_name => 'संस्कृतम्', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sc', :long_name => 'Sardinian', :localized_name => 'Sardu', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sd', :long_name => 'Sindhi', :localized_name => 'सिन्धी', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'se', :long_name => 'Northern Sami', :localized_name => 'Davvisámegiella', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sg', :long_name => 'Sango', :localized_name => 'yângâ tî sängö', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sh', :long_name => 'Serbo-Croatian', :localized_name => 'Српскохрватски', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'si', :long_name => 'Singhalese', :localized_name => 'සිංහල', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sk', :long_name => 'Slovak', :localized_name => 'Slovenčina', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sl', :long_name => 'Slovenian', :localized_name => 'Slovenščina', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sm', :long_name => 'Samoan', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sn', :long_name => 'Shona', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'so', :long_name => 'Somali', :localized_name => 'Soomaaliga', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sq', :long_name => 'Albanian', :localized_name => 'Shqip', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sr', :long_name => 'Serbian', :localized_name => 'Српски', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ss', :long_name => 'Siswati', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'st', :long_name => 'Sesotho', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'su', :long_name => 'Sudanese', :localized_name => 'Basa Sunda', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sv', :long_name => 'Swedish', :localized_name => 'Svenska', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'sw', :long_name => 'Swahili', :localized_name => 'Kiswahili', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ta', :long_name => 'Tamil', :localized_name => 'தமிழ்', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'te', :long_name => 'Telugu', :localized_name => 'తెలుగు', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'tg', :long_name => 'Tajik', :localized_name => 'тоҷикӣ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'th', :long_name => 'Thai', :localized_name => 'ภาษาไทย', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ti', :long_name => 'Tigrinya', :localized_name => 'ትግርኛ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'tk', :long_name => 'Turkmen', :localized_name => 'Түркмен', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'tl', :long_name => 'Tagalog', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'tn', :long_name => 'Setswana', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'to', :long_name => 'Tonga', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'tr', :long_name => 'Turkish', :localized_name => 'Türkçe', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ts', :long_name => 'Tsonga', :localized_name => 'Xitsonga', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'tt', :long_name => 'Tatar', :localized_name => 'Tatarça', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'tw', :long_name => 'Twi', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ty', :long_name => 'Tahitian', :localized_name => 'Reo Mā`ohi', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ug', :long_name => 'Uyghur', :localized_name => 'Uyƣurqə', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'uk', :long_name => 'Ukrainian', :localized_name => 'Українська', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'ur', :long_name => 'Urdu', :localized_name => 'اردو', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'uz', :long_name => 'Uzbek', :localized_name => "o'zbek", :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 've', :long_name => 'Venda', :localized_name => 'Tshivenḓa', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'vi', :long_name => 'Vietnamese', :localized_name => 'Tiếng Việt', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'wo', :long_name => 'Wolof', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'xh', :long_name => 'Xhosa', :localized_name => 'isiXhosa', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'yi', :long_name => 'Yiddish', :localized_name => 'ייִדיש',  :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'yo', :long_name => 'Yoruba', :localized_name => 'Yorùbá', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'za', :long_name => 'Zhuang', :localized_name => 'Saɯ cueŋƅ', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'zh-hans', :long_name => 'Chinese, Simplified', :localized_name => '简体中文', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'zh-hant', :long_name => 'Chinese, Traditional', :localized_name => '繁體中文', :allowed_in_profile => true, :translation_exists => false)
    Language.create!(:short_name => 'zu', :long_name => 'Zulu', :localized_name => 'isiZulu', :allowed_in_profile => true, :translation_exists => false)
  end

  def self.down
    remove_column :journals, :language_id
    remove_column :languages, :allowed_in_profile
    remove_column :languages, :localized_name

    # Return the languages table to its previous state (easier than deleting all the new languages one by one):
    Language.delete_all
    Language.create!(:short_name => 'en', :long_name => 'English', :translation_exists => true)
    Language.create!(:short_name => 'en-ca', :long_name => 'English (Canada)', :translation_exists => true)
  end
end
