class SetUpLocalizedLangsAndCountries < ActiveRecord::Migration
  def self.up
    drop_table :countries

    Language.all.each do |lang|
      lang.localized_name = lang.long_name if lang.localized_name.nil?
      lang.save!
    end

    remove_column :languages, :long_name
  end

  def self.down
    # Restore countries table
    create_table :countries do |t|
      t.string :name, :limit => 255, :null => false
    end
    ActionView::Helpers::FormOptionsHelper::COUNTRIES.each_with_index do |name, id|
      Country.create!(:id => id, :name => name)
    end

    # Restore languages table
    add_column :languages, :long_name, :string, :length => 30, :null => false, :after => :short_name
    Language.find_by_short_name('en').update_attributes!(:long_name => 'English', :localized_name => nil)
    Language.find_by_short_name('en-ca').update_attributes!(:long_name => 'English (Canada)', :localized_name => nil)
    Language.find_by_short_name('aa').update_attributes!(:long_name => 'Afar', :localized_name => nil)
    Language.find_by_short_name('ab').update_attributes!(:long_name => 'Abkhazian', :localized_name => "аҧсуа бызшәа")
    Language.find_by_short_name('ae').update_attributes!(:long_name => 'Avestan', :localized_name => nil)
    Language.find_by_short_name('af').update_attributes!(:long_name => 'Afrikaans', :localized_name => nil)
    Language.find_by_short_name('ak').update_attributes!(:long_name => 'Akan', :localized_name => nil)
    Language.find_by_short_name('am').update_attributes!(:long_name => 'Amharic', :localized_name => "አማርኛ")
    Language.find_by_short_name('ar').update_attributes!(:long_name => 'Arabic', :localized_name => "العربية")
    Language.find_by_short_name('as').update_attributes!(:long_name => 'Assamese', :localized_name => nil)
    Language.find_by_short_name('av').update_attributes!(:long_name => 'Avar', :localized_name => nil)
    Language.find_by_short_name('ay').update_attributes!(:long_name => 'Aymara', :localized_name => nil)
    Language.find_by_short_name('az').update_attributes!(:long_name => 'Azerbaijani', :localized_name => "azərbaycan")
    Language.find_by_short_name('ba').update_attributes!(:long_name => 'Bashkir', :localized_name => nil)
    Language.find_by_short_name('be').update_attributes!(:long_name => 'Belarusian', :localized_name => "Беларуская")
    Language.find_by_short_name('bg').update_attributes!(:long_name => 'Bulgarian', :localized_name => "Български")
    Language.find_by_short_name('bh').update_attributes!(:long_name => 'Bihari', :localized_name => "भोजपुरी")
    Language.find_by_short_name('bi').update_attributes!(:long_name => 'Bislama', :localized_name => nil)
    Language.find_by_short_name('bm').update_attributes!(:long_name => 'Bambara', :localized_name => "Bamanankan")
    Language.find_by_short_name('bn').update_attributes!(:long_name => 'Bengali', :localized_name => "বাংলা")
    Language.find_by_short_name('bo').update_attributes!(:long_name => 'Tibetan', :localized_name => "བོད་ཡིག")
    Language.find_by_short_name('br').update_attributes!(:long_name => 'Breton', :localized_name => nil)
    Language.find_by_short_name('bs').update_attributes!(:long_name => 'Bosnian', :localized_name => "Bosanski")
    Language.find_by_short_name('ca').update_attributes!(:long_name => 'Catalan', :localized_name => "Català")
    Language.find_by_short_name('ce').update_attributes!(:long_name => 'Chechen', :localized_name => "нохчийн мотт")
    Language.find_by_short_name('ch').update_attributes!(:long_name => 'Chamorro', :localized_name => nil)
    Language.find_by_short_name('co').update_attributes!(:long_name => 'Corsican', :localized_name => nil)
    Language.find_by_short_name('cr').update_attributes!(:long_name => 'Cree', :localized_name => "ᓀᐦᐃᔭᐍᐏᐣ")
    Language.find_by_short_name('cs').update_attributes!(:long_name => 'Czech', :localized_name => "Čeština")
    Language.find_by_short_name('cu').update_attributes!(:long_name => 'Old Church Slavonic', :localized_name => "ѩзыкъ словѣньскъ")
    Language.find_by_short_name('cv').update_attributes!(:long_name => 'Chuvash', :localized_name => "чӑваш чӗлхи")
    Language.find_by_short_name('cy').update_attributes!(:long_name => 'Welsh', :localized_name => "Cymraeg")
    Language.find_by_short_name('da').update_attributes!(:long_name => 'Danish', :localized_name => "Dansk")
    Language.find_by_short_name('de').update_attributes!(:long_name => 'German', :localized_name => "Deutsch")
    Language.find_by_short_name('dv').update_attributes!(:long_name => 'Dhivehi', :localized_name => "ދިވެހި")
    Language.find_by_short_name('dz').update_attributes!(:long_name => 'Dzongkha', :localized_name => "རྫོང་ཁ")
    Language.find_by_short_name('ee').update_attributes!(:long_name => 'Ewe', :localized_name => "Ɛʋɛ")
    Language.find_by_short_name('el').update_attributes!(:long_name => 'Greek', :localized_name => "Ελληνικά")
    Language.find_by_short_name('eo').update_attributes!(:long_name => 'Esperanto', :localized_name => nil)
    Language.find_by_short_name('es').update_attributes!(:long_name => 'Spanish', :localized_name => "Español")
    Language.find_by_short_name('et').update_attributes!(:long_name => 'Estonian', :localized_name => "Eesti")
    Language.find_by_short_name('eu').update_attributes!(:long_name => 'Basque', :localized_name => "Euskera")
    Language.find_by_short_name('fa').update_attributes!(:long_name => 'Persian', :localized_name => "فارسی")
    Language.find_by_short_name('ff').update_attributes!(:long_name => 'Fulah', :localized_name => "Fulfulde")
    Language.find_by_short_name('fi').update_attributes!(:long_name => 'Finnish', :localized_name => "Suomi")
    Language.find_by_short_name('fj').update_attributes!(:long_name => 'Fijian', :localized_name => nil)
    Language.find_by_short_name('fo').update_attributes!(:long_name => 'Faeroese', :localized_name => "Føroyskt")
    Language.find_by_short_name('fr').update_attributes!(:long_name => 'French', :localized_name => "Français")
    Language.find_by_short_name('fy').update_attributes!(:long_name => 'Frisian', :localized_name => "Frysk")
    Language.find_by_short_name('ga').update_attributes!(:long_name => 'Irish', :localized_name => "Gaeilge")
    Language.find_by_short_name('gd').update_attributes!(:long_name => 'Scottish Gaelic', :localized_name => "Gàidhlig")
    Language.find_by_short_name('gl').update_attributes!(:long_name => 'Galician', :localized_name => "Galego")
    Language.find_by_short_name('gn').update_attributes!(:long_name => 'Guaraní', :localized_name => "Avañe'ẽ")
    Language.find_by_short_name('gu').update_attributes!(:long_name => 'Gujarati', :localized_name => "ગુજરાતી")
    Language.find_by_short_name('gv').update_attributes!(:long_name => 'Manx', :localized_name => "Gaelg")
    Language.find_by_short_name('ha').update_attributes!(:long_name => 'Hausa', :localized_name => "هَوُسَ")
    Language.find_by_short_name('he').update_attributes!(:long_name => 'Hebrew', :localized_name => "עברית")
    Language.find_by_short_name('hi').update_attributes!(:long_name => 'Hindi', :localized_name => "हिन्दी")
    Language.find_by_short_name('ho').update_attributes!(:long_name => 'Hiri Motu', :localized_name => nil)
    Language.find_by_short_name('hr').update_attributes!(:long_name => 'Croatian', :localized_name => "Hrvatski")
    Language.find_by_short_name('hu').update_attributes!(:long_name => 'Hungarian', :localized_name => "Magyar")
    Language.find_by_short_name('hy').update_attributes!(:long_name => 'Armenian', :localized_name => "Հայերեն")
    Language.find_by_short_name('hz').update_attributes!(:long_name => 'Herero', :localized_name => "Otjiherero")
    Language.find_by_short_name('ia').update_attributes!(:long_name => 'Interlingua', :localized_name => nil)
    Language.find_by_short_name('id').update_attributes!(:long_name => 'Indonesian', :localized_name => "Bahasa Indonesia")
    Language.find_by_short_name('ie').update_attributes!(:long_name => 'Interlingue', :localized_name => nil)
    Language.find_by_short_name('ig').update_attributes!(:long_name => 'Igbo', :localized_name => nil)
    Language.find_by_short_name('ik').update_attributes!(:long_name => 'Inupiaq', :localized_name => "Iñupiaq")
    Language.find_by_short_name('is').update_attributes!(:long_name => 'Icelandic', :localized_name => "Íslenska")
    Language.find_by_short_name('it').update_attributes!(:long_name => 'Italian', :localized_name => "Italiano")
    Language.find_by_short_name('iu').update_attributes!(:long_name => 'Inuktitut', :localized_name => "ᐃᓄᒃᑎᑐᑦ")
    Language.find_by_short_name('ja').update_attributes!(:long_name => 'Japanese', :localized_name => "日本語")
    Language.find_by_short_name('jv').update_attributes!(:long_name => 'Javanese', :localized_name => "basa Jawa")
    Language.find_by_short_name('ka').update_attributes!(:long_name => 'Georgian', :localized_name => "ქართული")
    Language.find_by_short_name('kg').update_attributes!(:long_name => 'Kongo', :localized_name => "KiKongo")
    Language.find_by_short_name('ki').update_attributes!(:long_name => 'Gikuyu', :localized_name => "Gĩkũyũ")
    Language.find_by_short_name('kj').update_attributes!(:long_name => 'Kwanyama', :localized_name => nil)
    Language.find_by_short_name('kk').update_attributes!(:long_name => 'Kazakh', :localized_name => "Қазақ тілі")
    Language.find_by_short_name('kl').update_attributes!(:long_name => 'Kalaallisut', :localized_name => nil)
    Language.find_by_short_name('km').update_attributes!(:long_name => 'Khmer', :localized_name => "ភាសាខ្មែរ")
    Language.find_by_short_name('kn').update_attributes!(:long_name => 'Kannada', :localized_name => "ಕನ್ನಡ")
    Language.find_by_short_name('ko').update_attributes!(:long_name => 'Korean', :localized_name => "한국어")
    Language.find_by_short_name('kr').update_attributes!(:long_name => 'Kanuri', :localized_name => nil)
    Language.find_by_short_name('ks').update_attributes!(:long_name => 'Kashmiri', :localized_name => "कश्मीरी")
    Language.find_by_short_name('ku').update_attributes!(:long_name => 'Kurdish', :localized_name => "Kurdî")
    Language.find_by_short_name('kv').update_attributes!(:long_name => 'Komi', :localized_name => "коми кыв")
    Language.find_by_short_name('kw').update_attributes!(:long_name => 'Cornish', :localized_name => "Kernewek")
    Language.find_by_short_name('ky').update_attributes!(:long_name => 'Kirghiz', :localized_name => "кыргыз тили")
    Language.find_by_short_name('la').update_attributes!(:long_name => 'Latin', :localized_name => "Latina")
    Language.find_by_short_name('lb').update_attributes!(:long_name => 'Luxembourgish', :localized_name => "Lëtzebuergesch")
    Language.find_by_short_name('lg').update_attributes!(:long_name => 'Luganda', :localized_name => nil)
    Language.find_by_short_name('ln').update_attributes!(:long_name => 'Lingala', :localized_name => "Lingála")
    Language.find_by_short_name('lo').update_attributes!(:long_name => 'Laothian', :localized_name => "ພາສາລາວ")
    Language.find_by_short_name('lt').update_attributes!(:long_name => 'Lithuanian', :localized_name => "Lietuvių")
    Language.find_by_short_name('lv').update_attributes!(:long_name => 'Latvian', :localized_name => "Latviešu")
    Language.find_by_short_name('mg').update_attributes!(:long_name => 'Malagasy', :localized_name => nil)
    Language.find_by_short_name('mh').update_attributes!(:long_name => 'Marshallese', :localized_name => "Kajin M̧ajeļ")
    Language.find_by_short_name('mi').update_attributes!(:long_name => 'Maori', :localized_name => "te reo Māori")
    Language.find_by_short_name('mk').update_attributes!(:long_name => 'Macedonian', :localized_name => "Македонски")
    Language.find_by_short_name('ml').update_attributes!(:long_name => 'Malayalam', :localized_name => "മലയാളം")
    Language.find_by_short_name('mn').update_attributes!(:long_name => 'Mongolian', :localized_name => "Монгол")
    Language.find_by_short_name('mo').update_attributes!(:long_name => 'Moldavian', :localized_name => nil)
    Language.find_by_short_name('mr').update_attributes!(:long_name => 'Marathi', :localized_name => "मराठी")
    Language.find_by_short_name('ms').update_attributes!(:long_name => 'Malay', :localized_name => "Bahasa Melayu")
    Language.find_by_short_name('mt').update_attributes!(:long_name => 'Maltese', :localized_name => "Malti")
    Language.find_by_short_name('my').update_attributes!(:long_name => 'Burmese', :localized_name => "ဗမာစာ")
    Language.find_by_short_name('na').update_attributes!(:long_name => 'Nauruan', :localized_name => "Ekakairũ Naoero")
    Language.find_by_short_name('nd').update_attributes!(:long_name => 'North Ndebele', :localized_name => "isiNdebele")
    Language.find_by_short_name('ne').update_attributes!(:long_name => 'Nepali', :localized_name => "नेपाली")
    Language.find_by_short_name('ng').update_attributes!(:long_name => 'Ndonga', :localized_name => "Owambo")
    Language.find_by_short_name('nl').update_attributes!(:long_name => 'Dutch', :localized_name => "Nederlands")
    Language.find_by_short_name('nb').update_attributes!(:long_name => 'Norwegian Bokmål', :localized_name => "Bokmål")
    Language.find_by_short_name('nn').update_attributes!(:long_name => 'Norwegian Nynorsk', :localized_name => "Nynorsk")
    Language.find_by_short_name('nr').update_attributes!(:long_name => 'South Ndebele', :localized_name => "isiNdebele")
    Language.find_by_short_name('nv').update_attributes!(:long_name => 'Navajo', :localized_name => "Diné bizaad; Dinékʼehǰí")
    Language.find_by_short_name('ny').update_attributes!(:long_name => 'Chichewa', :localized_name => "chiCheŵa")
    Language.find_by_short_name('oc').update_attributes!(:long_name => 'Occitan', :localized_name => nil)
    Language.find_by_short_name('om').update_attributes!(:long_name => 'Oromo', :localized_name => "Afaan Oromoo")
    Language.find_by_short_name('or').update_attributes!(:long_name => 'Oriya', :localized_name => "ଓଡ଼ିଆ")
    Language.find_by_short_name('os').update_attributes!(:long_name => 'Ossetic', :localized_name => "Ирон æвзаг")
    Language.find_by_short_name('pa').update_attributes!(:long_name => 'Punjabi', :localized_name => "ਪੰਜਾਬੀ")
    Language.find_by_short_name('pi').update_attributes!(:long_name => 'Pāli', :localized_name => "पाऴि")
    Language.find_by_short_name('pl').update_attributes!(:long_name => 'Polish', :localized_name => "Polski")
    Language.find_by_short_name('ps').update_attributes!(:long_name => 'Pashto', :localized_name => "پښتو")
    Language.find_by_short_name('pt').update_attributes!(:long_name => 'Portuguese', :localized_name => "Português")
    Language.find_by_short_name('qu').update_attributes!(:long_name => 'Quechua', :localized_name => "Runa Simi")
    Language.find_by_short_name('rm').update_attributes!(:long_name => 'Rhaeto-Romance', :localized_name => nil)
    Language.find_by_short_name('rn').update_attributes!(:long_name => 'Kirundi', :localized_name => nil)
    Language.find_by_short_name('ro').update_attributes!(:long_name => 'Romanian', :localized_name => "Română")
    Language.find_by_short_name('ru').update_attributes!(:long_name => 'Russian', :localized_name => "Русский")
    Language.find_by_short_name('rw').update_attributes!(:long_name => 'Kinyarwanda', :localized_name => "Ikinyarwanda")
    Language.find_by_short_name('sa').update_attributes!(:long_name => 'Sanskrit', :localized_name => "संस्कृतम्")
    Language.find_by_short_name('sc').update_attributes!(:long_name => 'Sardinian', :localized_name => "Sardu")
    Language.find_by_short_name('sd').update_attributes!(:long_name => 'Sindhi', :localized_name => "सिन्धी")
    Language.find_by_short_name('se').update_attributes!(:long_name => 'Northern Sami', :localized_name => "Davvisámegiella")
    Language.find_by_short_name('sg').update_attributes!(:long_name => 'Sango', :localized_name => "yângâ tî sängö")
    Language.find_by_short_name('sh').update_attributes!(:long_name => 'Serbo-Croatian', :localized_name => "Српскохрватски")
    Language.find_by_short_name('si').update_attributes!(:long_name => 'Singhalese', :localized_name => "සිංහල")
    Language.find_by_short_name('sk').update_attributes!(:long_name => 'Slovak', :localized_name => "Slovenčina")
    Language.find_by_short_name('sl').update_attributes!(:long_name => 'Slovenian', :localized_name => "Slovenščina")
    Language.find_by_short_name('sm').update_attributes!(:long_name => 'Samoan', :localized_name => nil)
    Language.find_by_short_name('sn').update_attributes!(:long_name => 'Shona', :localized_name => nil)
    Language.find_by_short_name('so').update_attributes!(:long_name => 'Somali', :localized_name => "Soomaaliga")
    Language.find_by_short_name('sq').update_attributes!(:long_name => 'Albanian', :localized_name => "Shqip")
    Language.find_by_short_name('sr').update_attributes!(:long_name => 'Serbian', :localized_name => "Српски")
    Language.find_by_short_name('ss').update_attributes!(:long_name => 'Siswati', :localized_name => nil)
    Language.find_by_short_name('st').update_attributes!(:long_name => 'Sesotho', :localized_name => nil)
    Language.find_by_short_name('su').update_attributes!(:long_name => 'Sudanese', :localized_name => "Basa Sunda")
    Language.find_by_short_name('sv').update_attributes!(:long_name => 'Swedish', :localized_name => "Svenska")
    Language.find_by_short_name('sw').update_attributes!(:long_name => 'Swahili', :localized_name => "Kiswahili")
    Language.find_by_short_name('ta').update_attributes!(:long_name => 'Tamil', :localized_name => "தமிழ்")
    Language.find_by_short_name('te').update_attributes!(:long_name => 'Telugu', :localized_name => "తెలుగు")
    Language.find_by_short_name('tg').update_attributes!(:long_name => 'Tajik', :localized_name => "тоҷикӣ")
    Language.find_by_short_name('th').update_attributes!(:long_name => 'Thai', :localized_name => "ภาษาไทย")
    Language.find_by_short_name('ti').update_attributes!(:long_name => 'Tigrinya', :localized_name => "ትግርኛ")
    Language.find_by_short_name('tk').update_attributes!(:long_name => 'Turkmen', :localized_name => "Түркмен")
    Language.find_by_short_name('tl').update_attributes!(:long_name => 'Tagalog', :localized_name => nil)
    Language.find_by_short_name('tn').update_attributes!(:long_name => 'Setswana', :localized_name => nil)
    Language.find_by_short_name('to').update_attributes!(:long_name => 'Tonga', :localized_name => nil)
    Language.find_by_short_name('tr').update_attributes!(:long_name => 'Turkish', :localized_name => "Türkçe")
    Language.find_by_short_name('ts').update_attributes!(:long_name => 'Tsonga', :localized_name => "Xitsonga")
    Language.find_by_short_name('tt').update_attributes!(:long_name => 'Tatar', :localized_name => "Tatarça")
    Language.find_by_short_name('tw').update_attributes!(:long_name => 'Twi', :localized_name => nil)
    Language.find_by_short_name('ty').update_attributes!(:long_name => 'Tahitian', :localized_name => "Reo Mā`ohi")
    Language.find_by_short_name('ug').update_attributes!(:long_name => 'Uyghur', :localized_name => "Uyƣurqə")
    Language.find_by_short_name('uk').update_attributes!(:long_name => 'Ukrainian', :localized_name => "Українська")
    Language.find_by_short_name('ur').update_attributes!(:long_name => 'Urdu', :localized_name => "اردو")
    Language.find_by_short_name('uz').update_attributes!(:long_name => 'Uzbek', :localized_name => "o'zbek")
    Language.find_by_short_name('ve').update_attributes!(:long_name => 'Venda', :localized_name => "Tshivenḓa")
    Language.find_by_short_name('vi').update_attributes!(:long_name => 'Vietnamese', :localized_name => "Tiếng Việt")
    Language.find_by_short_name('wo').update_attributes!(:long_name => 'Wolof', :localized_name => nil)
    Language.find_by_short_name('xh').update_attributes!(:long_name => 'Xhosa', :localized_name => "isiXhosa")
    Language.find_by_short_name('yi').update_attributes!(:long_name => 'Yiddish', :localized_name => "ייִדיש")
    Language.find_by_short_name('yo').update_attributes!(:long_name => 'Yoruba', :localized_name => "Yorùbá")
    Language.find_by_short_name('za').update_attributes!(:long_name => 'Zhuang', :localized_name => "Saɯ cueŋƅ")
    Language.find_by_short_name('zh-hans').update_attributes!(:long_name => 'Chinese, Simplified', :localized_name => "简体中文")
    Language.find_by_short_name('zh-hant').update_attributes!(:long_name => 'Chinese, Traditional', :localized_name => "繁體中文")
    Language.find_by_short_name('zu').update_attributes!(:long_name => 'Zulu', :localized_name => "isiZulu")
    Language.find_by_short_name('zh').update_attributes!(:long_name => 'Chinese', :localized_name => "中文")
  end
end
